version: '3.3'

services:
  db:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    networks:
      - biblioteca-network
  
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - biblioteca-network

  app:
    container_name: biblioteca
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "rails db:create db:migrate db:seed && rails server"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - biblioteca-network

networks:
  biblioteca-network: 
    - "docker network create biblioteca-network"
  external: true